const BRAVE_CONNECT_WALLETS_ROUTE = '/connect-wallets'
const BRAVE_BITGO_INITIALIZE_ROUTE = '/initialize/bitgo'
const BRAVE_BITGO_WALLET_INDEX = '/bitgo/wallets'
const BRAVE_BITGO_WALLET_SEND_ROUTE = '/bitgo/wallets/send'

export {
  BRAVE_CONNECT_WALLETS_ROUTE,
  BRAVE_BITGO_INITIALIZE_ROUTE,
  BRAVE_BITGO_WALLET_INDEX,
  BRAVE_BITGO_WALLET_SEND_ROUTE,
}
